// Rock archetypes generated by the forge, not loaded from a GLB.
//
// Replaces assetRocks.js. The scanned `river_rocks.glb` was five stones, 14 MB, and
// a fixed cast — every bed was built from the same five silhouettes at different
// scales, and a rock's *appearance* had nothing to do with its physics because the
// two were authored separately.
//
// Generated rocks fix all three. The forge produces an unlimited cast from a seed,
// ships no asset, and — the point of the exercise — hands the same geometry to the
// renderer, the collision hull, the rating, and the skip solver. A stone that looks
// warped IS warped, in every system that touches it.
//
// Deliberately NOT ported here: the forge's own material and texture pipeline
// (rockMaterial.js, rockTextures.js, detailTextures.js — a baked atlas and a custom
// shader). Materials here are plain PBR built from each archetype's own colour and
// roughness, which is honest per-lithology shading without dragging a texture
// pipeline across a lab boundary. Porting the forge's shading is its own pass.

import { Mesh, PhysicsShapeConvexHull, VertexData, PBRMaterial, Color3 } from "@babylonjs/core";
import { bakeLibrary, buildDetailMesh, buildHullPoints } from "../../rock-forge/src/forge/bake.js";
import { ARCHETYPES } from "../../rock-forge/src/forge/archetypes.js";
import { detailedMetrics, SOLVER_LOD } from "../../rock-forge/src/forge/solverParams.js";
import { mulberry32 } from "./noise.js";

/**
 * Icosphere level for the VISUAL mesh. The bed holds hundreds of instances, so this
 * is the number that decides the frame budget — the physics copy is separate and
 * already coarse (SOLVER_LOD). Level 3 is 1280 triangles, close to what the scanned
 * stones cost after their own decimation.
 */
const VISUAL_LOD = 3;

/**
 * Points sampled for the collision hull. The forge's own note on `buildHullPoints`
 * is worth heeding: where the directions go matters far more than how many, because
 * evenly-spread directions spend themselves on the flat faces and miss the rim,
 * which is where the entire silhouette lives.
 */
const HULL_LOD = 3;

/**
 * Generate rock archetypes.
 *
 * Returns the same contract `loadRockArchetypes()` did — `{mesh, shape, vertexData,
 * material, metrics, family}` — so `field.js`, `bed.js` and `examine.js` are
 * unaffected. `mesh.name` is stable for a given (seed, count), which matters because
 * baked beds store stone names and resolve them back on load.
 *
 * @param scene            Babylon scene
 * @param opts.unitScale   world units per metre (config's `U`)
 * @param opts.count       how many distinct stones to generate
 * @param opts.seed        library seed; same seed gives the same cast every time
 */
export function createForgeArchetypes(scene, { unitScale = 1, count = 12, seed = 99 } = {}) {
  const lib = bakeLibrary({ count, seed });
  const rng = mulberry32(seed ^ 0x9e3779b9);
  const archetypes = [];

  for (const shape of lib.shapes) {
    const params = ARCHETYPES[shape.archetype];
    if (!params) continue;

    // Real-world size, drawn from the archetype's own range. Slate runs 4.5-10.5 cm,
    // a granite cobble is chunkier — the ranges are part of what makes a family read
    // as that family, so they are not overridden here.
    const [lo, hi] = shape.sizeRange ?? [0.04, 0.09];
    const sizeMetres = lo + (hi - lo) * rng();

    // Built ONCE, in metres. The renderer wants world units and the physics wants
    // metres, and scaling is linear, so the same vertices serve both — multiplying
    // for display rather than generating the rock twice.
    const detail = buildDetailMesh(shape, params, VISUAL_LOD, sizeMetres);

    const positions = new Float32Array(detail.positions.length);
    for (let i = 0; i < positions.length; i++) positions[i] = detail.positions[i] * unitScale;

    const vertexData = new VertexData();
    vertexData.positions = positions;
    vertexData.indices = Array.from(detail.indices);
    const normals = [];
    VertexData.ComputeNormals(positions, vertexData.indices, normals);
    vertexData.normals = normals;

    // Stable and unique: baked beds store these names and fail loudly on a mismatch.
    const name = `forge_${shape.archetype}_${shape.index}`;
    const mesh = new Mesh(name, scene);
    vertexData.applyToMesh(mesh, false);
    mesh.receiveShadows = true;

    const material = new PBRMaterial(`${name}_mat`, scene);
    const [r, g, b] = shape.colour;
    material.albedoColor = new Color3(r, g, b);
    material.roughness = shape.roughness ?? 0.7;
    material.metallic = 0;
    material.environmentIntensity = 0.85;
    material.backFaceCulling = true;
    material.twoSidedLighting = false;
    // VertexData built here uses Babylon's own winding, so the loader's compensating
    // flip (which assetRocks.js had to undo) never applies. `null` means defer to the
    // mesh. tools/winding-check.mjs is the guard.
    material.sideOrientation = null;
    mesh.material = material;

    // Collision hull from the forge's own direction set, not from the visual mesh:
    // it deliberately over-samples the rim, where a convex hull otherwise cuts the
    // silhouette badly on a flat stone.
    const hullPoints = buildHullPoints(shape, params, sizeMetres, HULL_LOD);
    const hullPositions = new Float32Array(hullPoints.length);
    for (let i = 0; i < hullPoints.length; i++) hullPositions[i] = hullPoints[i] * unitScale;
    const hullMesh = new Mesh(`${name}_hull`, scene);
    const hullData = new VertexData();
    hullData.positions = hullPositions;
    // A point cloud has no faces; the hull builder only reads positions, but Babylon
    // wants a valid index buffer, so give it a degenerate one.
    hullData.indices = [0, 1, 2];
    hullData.applyToMesh(hullMesh, false);
    hullMesh.isVisible = false;

    const physicsShape = new PhysicsShapeConvexHull(hullMesh, scene);
    physicsShape.material = { friction: 0.62, restitution: 0.06 };
    hullMesh.dispose(false, false);

    // Metrics measured off the real geometry — flatness and asymmetry from the
    // inertia tensor, and the true centre-of-mass offset, which bounding dimensions
    // cannot see. Computed at SOLVER_LOD, the same copy the water reads.
    const metrics = detailedMetrics(shape, params, sizeMetres, { level: SOLVER_LOD });
    metrics.family = shape.archetype;
    metrics.label = shape.label ?? params.label ?? "Stone";
    metrics.massKgWorld = metrics.massKg;
    metrics.volumeReal = metrics.volume;
    metrics.sizeMetres = sizeMetres;
    // Kept so the throw path can rebuild the exact same stone for the solver.
    metrics.forge = { shape, params, sizeMetres };

    archetypes.push({
      mesh, shape: physicsShape, vertexData, material, metrics, family: shape.archetype,
    });
  }

  return archetypes;
}
